[Fix] Correct syntax errors in VMware adapter applyVMwareDefaults
Removed erroneous 'var' keywords before if statements that were
causing compilation errors. Changed to proper short variable
declarations using ':=' syntax.

Resolves syntax errors:
- internal/adapters/vmware/adapter.go:210:6
- internal/adapters/vmware/adapter.go:212:6
- internal/adapters/vmware/adapter.go:215:6
- internal/adapters/vmware/adapter.go:217:6
- internal/adapters/vmware/adapter.go:220:6
- internal/adapters/vmware/adapter.go:222:6